name: Build Tauri App

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npm run build:linux

      - name: Build for Windows
        run: npm run build:windows

      - name: Build for macOS
        run: npm run build:macos

      # You can add more steps for additional platforms as needed
