name: Update Latest JSON on GitHub Pages

on:
  release:
    types: [published]

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
        
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get the latest release
        id: get_release
        run: echo "::set-output name=release_tag::${{ github.event.release.tag_name }}"

      - name: Download latest.json from release
        run: |
          curl -L -o latest.json \
          $(curl -s https://api.github.com/repos/ocallaje/seqworks/releases/latest \
          | jq -r '.assets[] | select(.name == "latest.json") | .browser_download_url')

      - name: Checkout the gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Update latest.json in gh-pages branch
        run: |
          mv latest.json ./updater.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest.json
          git commit -m "Update latest.json for release ${{ steps.get_release.outputs.release_tag }}"
          git push origin gh-pages
