name: Update GitHub Pages with Updater

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
        
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Get the latest release
        id: get_release
        run: echo "::set-output name=release_tag::${{ github.event.release.tag_name }}"

      - name: Download latest.json from release
        run: |
          curl -L -o updater.json \
          $(curl -s https://api.github.com/repos/ocallaje/seqworks/releases/latest \
          | jq -r '.assets[] | select(.name == "latest.json") | .browser_download_url')

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add updater.json
          git commit -m "Update updater.json for release ${{ steps.get_release.outputs.release_tag }}"
          git push origin gh-pages
